# Generated by Django 4.2.7 on 2023-11-24 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('publication_year', models.IntegerField(verbose_name='Год издания')),
                ('isbn', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN должен иметь формат 978-5-699-12014-7', regex='^\\d{3}-\\d-\\d{3,5}-\\d{5,7}-\\d$')], verbose_name='ISBN')),
            ],
        ),
    ]
